name: miincode
description: A project ro create and reade code QR and +.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2
  firebase_auth: #0.14.0+5
  google_sign_in: #^4.0.7
  http: #^0.12.0
  shared_preferences: ^0.5.3+4
  qrcode_plugin: ^0.0.2
  qr: ^1.2.0

  countdown_flutter: ^0.1.1
  
  expandable: ^3.0.0+1
  get_it: ^1.0.3
  
  sqflite:
  intl:
  flutter_datetime_picker:
    
  url_launcher: ^5.0.3
  image_picker: #'0.1.1'
  mime_type:

  encrypt: ^3.3.1

  # Controlar errores
  logger: #^0.7.0+2

  path_provider: ^1.1.0
  
  # Utilizado para manejar ESTADOS en --> LoginState
  provider: ^2.0.1
  
  
  async_loader: ^0.1.2
  #path: 

  #Shared--------------------------------------------
  esys_flutter_share: ^1.0.0

  #-----------------------------------------------------
  
  # Utilizado para Verificar si Hay o NO internet en el equipo
  connectivity: ^0.4.2
  # ----------------------------------------------------------

  # Agregado el 31-08-2019 --> COMPARTIR Imagenes--------
  # image_picker_saver: ^0.1.0
  # http: ^0.12.0+2

  flutter_email_sender: ^2.0.3
  mailer: ^3.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  
  


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon-miincode.png"
  adaptive_icon_background: "assets/icon/icon-miincode.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/icon/
  - assets/images/
  - assets/images/4.0x/logo_yakka.png
  - assets/QRCodeGenerado.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
